apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- role-binding.yaml
- servicerolebinding.yaml

configMapGenerator:
- name: profile-meta
  env: params.env

vars:
- name: PROFILE_NAMESPACE
  objref:
    kind: ConfigMap
    name: profile-meta
    apiVersion: v1
  fieldref:
    fieldpath: data.PROFILE_NAMESPACE

- name: PROFILE_USER
  objref:
    kind: ConfigMap
    name: profile-meta
    apiVersion: v1
  fieldref:
    fieldpath: data.PROFILE_USER


configurations:
- params.yaml
